- name: Create backup directory
  ansible.builtin.file:
    path: "/backups/"
    state: directory
    mode: '0771'
    owner: 'root'
    group: 'root'
- name: Check whether postgresql is available
  become: true
  become_user: postgres
  community.postgresql.postgresql_info:
  register: db_info
  ignore_errors: true
- block:
    - name: Create backup directory
      ansible.builtin.file:
        path: "/backups/database/"
        state: directory
        mode: '0770'
        owner: 'postgres'
        group: 'root'
    - name: Create backup of database
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ POSTGRESQL_CKAN_DATABASE }}"
        state: dump
        target: "/backups/database/backup_db_{{ POSTGRESQL_CKAN_DATABASE }}_{{ now(utc=true,fmt='%Y-%m-%d_%H.%M.%S') }}_ansible.pgc"
    - name: Remove all but the latest 100 dumps
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          find /backups/database/ -type f | sort -r | awk 'NR>100' | xargs --no-run-if-empty rm
  when: db_info.databases is defined and POSTGRESQL_CKAN_DATABASE in db_info.databases
