- hosts: dcorservers
  tasks:
    - name: Hard-coded backup file
      set_fact:
         restore_path_local: "{{ playbook_dir }}/backups/host-{{ inventory_hostname }}/restore_instance.tar.bz2"

    - name: Check whether we have a restore file
      local_action: stat path={{ restore_path_local }}
      register: restore_file_stat

    - name: Perform actual restore
      block:
        - name: maintenance mode on
          include_role:
            name: maintenance
          vars:
            maintenance_mode: true

        - name: restore from backup
          include_role:
            name: backup
          vars:
            backup_mode: "restore"

        - name: maintenance mode off
          include_role:
            name: maintenance
          vars:
            maintenance_mode: false

      when: restore_file_stat.stat.exists
