- name: provide minio
  include_tasks: provide-minio.yml
  when: DCOR_USE_LOCAL_MINIO | bool

- name: provide dcor
  include_tasks: provide-dcor.yml

- name: provide cron
  include_tasks: provide-cron.yml

- name: summary email
  include_tasks: send-summary-email.yml
