# https://github.com/hifis-net/ansible-collection-toolkit/tree/main/roles/unattended_upgrades
- name: Setup unattended upgrades
  include_role:
    name: hifis.toolkit.unattended_upgrades
  vars:
    unattended_automatic_reboot: true
    unattended_automatic_reboot_time: "00:01"
    unattended_mail_report: "{{ MAINTAINER_EMAIL }}"

- name: Install mailx and ssmtp for email notification
  ansible.builtin.apt:
    name:
    - bsd-mailx
    - ssmtp
  when: EMAIL_SMTP_SERVER != ""

- name: Setup email credentials
  ansible.builtin.template:
    src: "etc_ssmtp.conf.j2"
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: mail
    mode: '0640'
  when: EMAIL_SMTP_SERVER != ""

- name: Install needrestart for automated reboots
  ansible.builtin.apt:
    name: needrestart

- name: Configure needrestart to automatically reboot
  ansible.builtin.copy:
    dest: /etc/needrestart/conf.d/restart_mode_automatic.conf
    content: |
      # Set restart mode to automatic
      "$nrconf{restart} = 'a';"
