CKAN_INI_SITE_TITLE: "DCOR Playground"
CKAN_INI_AUTH_CREATE_USER_VIA_API: true
CKAN_INI_AUTH_CREATE_USER_VIA_WEB: true

DCOR_S3_BUCKET_NAME_STUB: "circle-dev"
DCOR_FAVICON_COLOR: "#a47f45"

DCOR_DEVELOP: true
DCOR_FIGSHARE_IMPORT: true
