CKAN_INI_SITE_TITLE: "DCOR Staging"
CKAN_INI_AUTH_CREATE_USER_VIA_API: true
CKAN_INI_AUTH_CREATE_USER_VIA_WEB: true
CKAN_INI_DCOR_SCHEMAS_ALLOW_CONTENT_LISTING_FOR_ANON: true
CKAN_INI_DCOR_SCHEMAS_ALLOW_PUBLIC_DATASETS: true

DCOR_USE_LOCAL_MINIO: true
DCOR_DEVELOP: true
DCOR_HTTPS_ENABLED: false
DCOR_FIGSHARE_IMPORT: false

DCOR_S3_BUCKET_NAME_STUB: "circle-test"

UWSGI_NUM_WORKERS: 2

FULLY_QUALIFIED_DOMAIN_NAME: "{{ ansible_default_ipv4.address }}"
